### ISSUE TITLE
Incorrect comparison outputs between transit + bikeshare <> transit

### ISSUE THREAD

**Issue by kuanb** [sidewalklabs/totx#65]
### Issue:
When comparing access isochrones, between transit + bike share and bike share, we/I would expect that transit _ bike share would beat or be comparable to bike share only everywhere. Yet, in the rendered outputs, bike share only beats the combined mode choice alternative. This appears counterintuitive. Perhaps the routing tool aggressively points assigns people to transit mode when walk would be faster and, in such cases, bike (+ walk) beats transit + bike (+ walk).

Similarly, when comparing transit + bike to just bike, we encounter another bizarre situation. Here, we would assume that transit + bike would indeed offer performance and access increases over solely transit (+ walk) and, yet, we see full parity in the modes across the map.

### Examples:
At any rate, the results are a bit confusing. See below image for example of the first situation:
![image](https://user-images.githubusercontent.com/6053396/40246250-f8f9d81e-5a7c-11e8-86ea-036aacf2d78b.png)

Example image capturing the second issue below:
![image](https://user-images.githubusercontent.com/6053396/40246263-06332616-5a7d-11e8-9a7f-fb5bb6e63800.png)

### Potential hotfix:
Pending better understanding of agent controls in R5 (configurable, and, with some work, would allow for better handling of mode choice comparisons), I propose the following hotfix:

1. For composite modes (such as Transit + Bikeshare), run 3 scenarios representing all permutations of the mode combinations (that is:
     - Bike only accessibility
     - Transit only accessibility
     - Transit + Bike acessiblity
2. Then layer all three results and select the one for each cell (using a distance matrix as a metaphor here) that is the lowest value.

From a technical standpoint, it shouldn't be difficult to compute. In addition, if all values are pre-computed (I assume so), then you simple make the composite mode query (such as Transit + Bike) query all three mode type endpoints and do a quick assessment of which is the lowest value.

Thus, when rendering the choropleth, each geometry in the Toronto composite shape would represent the results of the min value from all three related choropleths for the composite mode compared against the other share. Doing this would result in a valid choropleth via a defensible methodology with limited additional development.

API call that could be hacked:
https://github.com/sidewalklabs/totx/blob/4662cc30a3f2cb5b5cc7cbf1b9f7f8fa3b72649c/packages/transit/server/server.ts#L55-L65

Possible solution:
Map combined modes to 2 separate queries, one for each component of the combined mode permutation and then map those results, plus the combined, to a processor that selects the min value for each geometry.

More work:
https://github.com/sidewalklabs/totx/blob/d1df10edeba32a2424dcc6ea486f33712d2b644e/packages/transit/src/datastore.ts#L122-L135

Review default options and see if sensitivities there impact comparative access levels. PS I'd argue the 1 transfer restriction is too severe.

**Comment by kuanb** [comment]
@samaratrilling 

Apologies as I just saw the response. I think the inclusive methodology makes far more sense. I work on a network accessibility model (http://help.urbanfootprint.io/analyzing-scenarios/how-to-use-analytics-modules/walk-and-transit-accessibility-analytics) and this is the preferred path we've observed with our users. We have more limited mode options (walk, or walk + transit), but the use case is still comparable, I think, in the sense that the transit option is additive.

That is, all original graph nodes/edges are retained. If a modeled agent path is more efficient when walk only, that is the path that will be selected for that O/D pair, regardless if additional modes are present. As a result, no geometry has a value higher than the "base" for a joint mode share option.

Specifically: no walk + transit exceeds in time cost the O/D weight of walk-only journey. Values can only go down.

**Comment by samaratrilling** [comment]
Hi Kuan,
Thanks for your note on this.
It definitely makes sense in that in a single journey model, you should be recommended the fastest mode of transit even if you've selected multiple other slower ones.

In a comparison map, though, that approach has the drawback that in a comparison between transit and transit+bikeshare where it's always faster to just take transit, the map would be completely beige. This might leave the user with the mistaken impression that it's always equally fast to take transit or to take transit + bikeshare part of the way. In other words, this would effectively reduce the comparison to a transit vs transit comparison without making this clear to the user.

Since we've open-sourced the tool and are not actively adding or changing features for the time being, I'm going to go ahead and keep the current comparison scheme for the time being, but I agree it's a fruitful area for discussion of the user experience. If you want to submit a PR with an alternative option to continue the discussion, I'm of course happy to take a look and re-evaluate.

Thanks so much again for checking out the tool and helping evaluate it!

**Comment by kuanb** [comment]
Just to clarify, our tool does accessibility at all nodes in the system to all other nodes (effectively a full - but optimized - distance matrix) - similar to this tool. It is not a single journey tool. It is from user feedback that we've identified the cumulative pattern as being more legible to end users.

The example of transit vs transit + bikeshare would enable 5 possible mode combos:
- walk only
- bike only
- walk + bike
- walk + transit
- walk + bike + transit

Thus, in your example of transit vs transit + bikeshare (or any such comparison in Toronto), I'd be quite surprised if you ended up with that beige-only results.

**Comment by samaratrilling** [comment]
Ah, thanks for the clarification on your tool. That's awesome.

That breakdown makes sense - maybe what it'd make sense to do then is to have more than two colors on the map, so you could indicate where each of those 5 mode combinations is the fastest.
