### ISSUE TITLE
Incorrect comparison between transit modes on changing departure times

### ISSUE THREAD

**Issue by akshatg42** [sidewalklabs/totx#70]
In 'compare-settings' mode, on changing the departure time it only changes for mode A and remains the same for mode B. This leads to wrong comparison and wrong heatmap. 

Easy to reproduce example is when comparing transit with transit and changing the departure time once. The correct heat map should be all beige, but the one created is not. 

<img width="1680" alt="screen shot 2018-06-20 at 14 32 54" src="https://user-images.githubusercontent.com/22481473/41661512-de027302-7496-11e8-9b6f-39a8892995fd.png">

Fix - In **datastore.ts** in the function `handleSetOptions(action: actions.SetOptions)` add the following before `getCommuteTimePromises()` call: 

```
if (action.options.departure_time && mode === 'compare-settings'){
  options2.departure_time = options.departure_time;
}

```
This makes sure that on changing the departure_time, it changes for both modes and the comparison is thus correct.

**Comment by samaratrilling** [comment]
Hi Akshat,
Awesome, thanks for finding! Since you've identified a solution, do you want to go ahead and submit a pull request? I'd be happy to review and merge it.

**Comment by akshatg42** [comment]
Hi
I have submitted a pull request with the fix. I am not sure why it's failing the test on Circleci, it's working fine on my system

**Comment by samaratrilling** [comment]
I think if you run ‘yarn prettier’ and rerun, the tests should pass.

**Comment by akshatg42** [comment]
Yeah, it works now. Have a look.

**Comment by samaratrilling** [comment]
Great, merged and rolled out to production. Can you confirm that totx.sidewalklabs.com shows the expected changes?

**Comment by akshatg42** [comment]
Yes, it does.
