### ISSUE TITLE
Interaction not working when using AdBlock/uBlock

### ISSUE THREAD

**Issue by joined** [sidewalklabs/totx#73]
Using an ad-blocker extension like AdBlock or uBlock, which prevent the loading of Google Analytics, makes the visualization unusable. 

Every interaction results in this error:
![screenshot from 2018-06-29 10-07-16](https://user-images.githubusercontent.com/7922312/42080848-3b975d18-7b84-11e8-8490-4d0a57c38c5b.png)

The problem is in [totx/packages/transit/src/datastore.ts](https://github.com/sidewalklabs/totx/blob/d1df10edeba32a2424dcc6ea486f33712d2b644e/packages/transit/src/datastore.ts#L293-L295): if Google Analytics is not loaded, `ga()` is undefined and therefore the whole script crashes.

I think that a check like `if (typeof ga !== 'undefined')` on the `ga` method call should be enough to prevent this.

**Comment by danvk** [comment]
Hi @joined that's a great point. We should make all references to `ga` in JavaScript conditional in case users have a plugin that blocks it.

Another possible way to do this would be to make `ga`'s type `UniversalAnalytics.ga|null`, which would make the TypeScript compiler catch all these bugs for us.

Would you like to send a PR to fix this issue? If not, either @samaratrilling or I can handle it.

**Comment by danvk** [comment]
(Fixed by #74)
